linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - bodyclose
    - noctx
    - unconvert

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
