SHELL := /bin/bash
.DEFAULT_GOAL := help

.PHONY: help build test lint fmt docker-up docker-down swag migrate

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

build: ## Build all Go services
	go build fleet/shared/...
	go build fleet/vehicle-service/...
	go build fleet/telemetry-service/...
	go build fleet/alert-service/...
	go build fleet/simulator/...

test: ## Run all Go unit tests with race detector
	go test -race -count=1 fleet/shared/...
	go test -race -count=1 fleet/vehicle-service/...
	go test -race -count=1 fleet/telemetry-service/...
	go test -race -count=1 fleet/alert-service/...
	go test -race -count=1 fleet/simulator/...

lint: ## Run golangci-lint on all services
	cd shared && golangci-lint run ./...
	cd services/vehicle-service && golangci-lint run ./...
	cd services/telemetry-service && golangci-lint run ./...
	cd services/alert-service && golangci-lint run ./...
	cd apps/simulator && golangci-lint run ./...

fmt: ## Format all Go code
	gofmt -w shared/
	gofmt -w services/vehicle-service/
	gofmt -w services/telemetry-service/
	gofmt -w services/alert-service/
	gofmt -w apps/simulator/

docker-up: ## Start infrastructure containers
	docker compose up -d postgres redis rabbitmq

docker-down: ## Stop all containers
	docker compose down

docker-all: ## Start all containers including services
	docker compose up -d

swag: ## Generate Swagger docs (vehicle-service example)
	cd services/vehicle-service && swag init --parseDependency --parseInternal \
		-g ./cmd/api/main.go --output ./docs --outputTypes json,yaml

generate: ## Run go generate for all mocks
	go generate fleet/vehicle-service/...
	go generate fleet/telemetry-service/...
	go generate fleet/alert-service/...
	go generate fleet/simulator/...

web-dev: ## Start web dev server
	cd apps/web && npm run dev

web-build: ## Build web app
	cd apps/web && npm run build
