// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	"time"

	domain "fleet/alert-service/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// AlertService is an autogenerated mock type for the AlertService type
type AlertService struct {
	mock.Mock
}

// CreateAlert provides a mock function with given fields: ctx, vehicleID, alertType, startedAt
func (_m *AlertService) CreateAlert(ctx context.Context, vehicleID string, alertType string, startedAt time.Time) (domain.Alert, error) {
	ret := _m.Called(ctx, vehicleID, alertType, startedAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlert")
	}

	var r0 domain.Alert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (domain.Alert, error)); ok {
		return rf(ctx, vehicleID, alertType, startedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) domain.Alert); ok {
		r0 = rf(ctx, vehicleID, alertType, startedAt)
	} else {
		r0 = ret.Get(0).(domain.Alert)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, vehicleID, alertType, startedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *AlertService) GetAll(ctx context.Context) ([]domain.Alert, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Alert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Alert, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Alert); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Alert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOpenByVehicle provides a mock function with given fields: ctx, vehicleID
func (_m *AlertService) GetOpenByVehicle(ctx context.Context, vehicleID string) (domain.Alert, bool, error) {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenByVehicle")
	}

	var r0 domain.Alert
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Alert, bool, error)); ok {
		return rf(ctx, vehicleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Alert); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		r0 = ret.Get(0).(domain.Alert)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, vehicleID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, vehicleID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResolveAlert provides a mock function with given fields: ctx, vehicleID
func (_m *AlertService) ResolveAlert(ctx context.Context, vehicleID string) error {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAlertService creates a new instance of AlertService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAlertService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertService {
	mock := &AlertService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
