// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "fleet/vehicle-service/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// VehicleRepository is an autogenerated mock type for the VehicleRepository type
type VehicleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, v
func (_m *VehicleRepository) Create(ctx context.Context, v domain.Vehicle) (domain.Vehicle, error) {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Vehicle) (domain.Vehicle, error)); ok {
		return rf(ctx, v)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Vehicle) domain.Vehicle); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Get(0).(domain.Vehicle)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Vehicle) error); ok {
		r1 = rf(ctx, v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsByExternalID provides a mock function with given fields: ctx, externalID
func (_m *VehicleRepository) ExistsByExternalID(ctx context.Context, externalID string) (bool, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByExternalID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, externalID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsByPlate provides a mock function with given fields: ctx, plate
func (_m *VehicleRepository) ExistsByPlate(ctx context.Context, plate string) (bool, error) {
	ret := _m.Called(ctx, plate)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByPlate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, plate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, plate)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, plate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *VehicleRepository) GetAll(ctx context.Context) ([]domain.Vehicle, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Vehicle, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Vehicle); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VehicleRepository) GetByID(ctx context.Context, id string) (domain.Vehicle, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Vehicle, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Vehicle); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Vehicle)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *VehicleRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, v
func (_m *VehicleRepository) Update(ctx context.Context, v domain.Vehicle) (domain.Vehicle, error) {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Vehicle) (domain.Vehicle, error)); ok {
		return rf(ctx, v)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Vehicle) domain.Vehicle); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Get(0).(domain.Vehicle)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Vehicle) error); ok {
		r1 = rf(ctx, v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVehicleRepository creates a new instance of VehicleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehicleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VehicleRepository {
	mock := &VehicleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
