// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "fleet/telemetry-service/internal/core/domain"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// TelemetryCache is an autogenerated mock type for the TelemetryCache type
type TelemetryCache struct {
	mock.Mock
}

// CheckDedup provides a mock function with given fields: ctx, key
func (_m *TelemetryCache) CheckDedup(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CheckDedup")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetDedup provides a mock function with given fields: ctx, key, ttl
func (_m *TelemetryCache) SetDedup(ctx context.Context, key string, ttl time.Duration) error {
	ret := _m.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetDedup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, key, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastPosition provides a mock function with given fields: ctx, vehicleID
func (_m *TelemetryCache) GetLastPosition(ctx context.Context, vehicleID string) (domain.TelemetryPoint, bool, error) {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastPosition")
	}

	var r0 domain.TelemetryPoint
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.TelemetryPoint, bool, error)); ok {
		return rf(ctx, vehicleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.TelemetryPoint); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		r0 = ret.Get(0).(domain.TelemetryPoint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, vehicleID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, vehicleID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetLastPosition provides a mock function with given fields: ctx, vehicleID, point, ttl
func (_m *TelemetryCache) SetLastPosition(ctx context.Context, vehicleID string, point domain.TelemetryPoint, ttl time.Duration) error {
	ret := _m.Called(ctx, vehicleID, point, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetLastPosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TelemetryPoint, time.Duration) error); ok {
		r0 = rf(ctx, vehicleID, point, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTelemetryCache creates a new instance of TelemetryCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelemetryCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelemetryCache {
	mock := &TelemetryCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
