// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "fleet/telemetry-service/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// TelemetryRepository is an autogenerated mock type for the TelemetryRepository type
type TelemetryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, point
func (_m *TelemetryRepository) Create(ctx context.Context, point domain.TelemetryPoint) (domain.TelemetryPoint, error) {
	ret := _m.Called(ctx, point)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.TelemetryPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TelemetryPoint) (domain.TelemetryPoint, error)); ok {
		return rf(ctx, point)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TelemetryPoint) domain.TelemetryPoint); ok {
		r0 = rf(ctx, point)
	} else {
		r0 = ret.Get(0).(domain.TelemetryPoint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TelemetryPoint) error); ok {
		r1 = rf(ctx, point)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWithOutbox provides a mock function with given fields: ctx, point, event
func (_m *TelemetryRepository) CreateWithOutbox(ctx context.Context, point domain.TelemetryPoint, event domain.OutboxEvent) (domain.TelemetryPoint, error) {
	ret := _m.Called(ctx, point, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOutbox")
	}

	var r0 domain.TelemetryPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TelemetryPoint, domain.OutboxEvent) (domain.TelemetryPoint, error)); ok {
		return rf(ctx, point, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TelemetryPoint, domain.OutboxEvent) domain.TelemetryPoint); ok {
		r0 = rf(ctx, point, event)
	} else {
		r0 = ret.Get(0).(domain.TelemetryPoint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TelemetryPoint, domain.OutboxEvent) error); ok {
		r1 = rf(ctx, point, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByVehicleID provides a mock function with given fields: ctx, vehicleID
func (_m *TelemetryRepository) GetByVehicleID(ctx context.Context, vehicleID string) ([]domain.TelemetryPoint, error) {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for GetByVehicleID")
	}

	var r0 []domain.TelemetryPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.TelemetryPoint, error)); ok {
		return rf(ctx, vehicleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.TelemetryPoint); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TelemetryPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, vehicleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTelemetryRepository creates a new instance of TelemetryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelemetryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelemetryRepository {
	mock := &TelemetryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
